### ISSUE TITLE
Display tree of exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-dashboard#67]
On the maintaining page, there is an option to display a tree of the exercises (e.g. https://v3.exercism.io/csharp/maintaining/tree). This is currently not implemented, but it should show a tree of the exercises and their dependencies. @neenjaw has implemented this nicely in this codepen: https://codepen.io/neenjaw/pen/eYJpGRQ It would be great if we could "borrow' that code and use it in the dashboard to display the tree.

**Comment by neenjaw** [comment]
I'm interested in helping with this, but I have a few questions to source out some requirements.

- Given default bootstrap is the theme, should that carry over?
  - Can you describe what kind of look you would like it to have?
- Given it will be an svg, it can be resized losslessly, 
  - but can you specify the dimensions you will want for the dashboard.
- Because I would need to migrate the display from D3 to React, I would need to do some research how to draw the bezier curves from one node to another.  If there are any react examples of this workflow/algorithm, it would be useful.

@SleeplessByte Do you have any thoughts in regard to this?

**Comment by neenjaw** [comment]
I have ported my codepen code to typescript.  There is a rough start of this effort on my branch in my fork here: https://github.com/neenjaw/exercism-v3-dashboard/tree/tree-graph/src/components/graph

**Comment by neenjaw** [comment]
Right now there is still some logic in grapher.ts but I plan on moving that into ExerciseTreeGraph.tsx

**Comment by SleeplessByte** [comment]
(I've talked to @neenjaw via Slack to resolve some of this)

**Comment by neenjaw** [comment]
![Screenshot from 2020-06-20 17-08-10](https://user-images.githubusercontent.com/8953691/85213246-fb01af00-b318-11ea-8ac5-7a22249142f7.png)

A proof of concept!

**Comment by neenjaw** [comment]
![Screenshot from 2020-06-21 00-16-48](https://user-images.githubusercontent.com/8953691/85218172-e17e5880-b354-11ea-9d5d-68b93b6be3be.png)

**Comment by ErikSchierboom** [comment]
@neenjaw @SleeplessByte This is now live! Thanks for implementing this!

**Comment by neenjaw** [comment]
:tada: See #71 for another hot fix for the css.  I'm not sure how this passed this far.
